# Generated by Django 3.2.7 on 2021-10-12 01:56

import ctdb.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ioure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuid1', models.CharField(db_index=True, max_length=12, verbose_name='学号1')),
                ('stuid2', models.CharField(db_index=True, max_length=12, verbose_name='学号2')),
                ('moneynum', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='金额')),
                ('brrowimg', models.ImageField(upload_to=ctdb.models.iouimg_directory_path, verbose_name='照片')),
                ('brrowdate', models.DateTimeField(auto_now_add=True, verbose_name='借款时间')),
                ('brrowbackdate', models.DateField(verbose_name='还款期限')),
                ('timetemp', models.DateTimeField(auto_now=True, verbose_name='修改日期')),
                ('flag', models.BooleanField(default=False, verbose_name='是否存在')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wxid', models.CharField(max_length=20, null=True, unique=True, verbose_name='微信号')),
                ('stuid', models.CharField(max_length=12, unique=True, verbose_name='学号')),
                ('password', models.CharField(default='123456', max_length=20, verbose_name='密码')),
                ('name', models.CharField(max_length=11, verbose_name='姓名')),
                ('phonenum', models.CharField(max_length=11, verbose_name='联系方式')),
            ],
        ),
    ]
