# Generated by Django 3.2.7 on 2021-10-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='wxid',
            field=models.CharField(max_length=32, null=True, unique=True, verbose_name='微信号'),
        ),
    ]
